// pricing.js — single source of truth for all plan data
//  Import PRICING_TIERS wherever pricing info is needed.

export const PRICING_TIERS = [
    {
        id: "free",
        name: "Free",
        price: 0,
        yearlyPrice: 0,
        period: "month",
        description: "Get started with real-time polling — no credit card required.",
        badge: null,
        cta: "Get Started",
        ctaVariant: "outline", // outline | solid | accent
        limits: {
            authPolls: 5,
            anonPolls: 2,
            questionsPerPoll: 5,
            optionsPerQuestion: 4,
            analyticsRetention: "7 days",
            responseHistory: 1000,
            maxRespondentsPerPoll: 50,
            customBranding: false,
            exportResults: false,
            prioritySupport: false,
            apiAccess: false,
            webhooks: false,
        },
        features: [
            { label: "5 authenticated polls / month", included: true },
            { label: "2 anonymous polls / month", included: true },
            { label: "Up to 5 questions per poll", included: true },
            { label: "50 respondents per poll", included: true },
            { label: "Basic analytics (7-day retention)", included: true },
            { label: "100 response history", included: true },
            { label: "Shareable poll links", included: true },
            { label: "Real-time response updates", included: true },
            { label: "Advanced analytics", included: false },
            { label: "Export results (CSV / JSON)", included: false },
            { label: "Custom branding", included: false },
            { label: "API access", included: false },
            { label: "Priority support", included: false },
        ],
    },
    {
        id: "go",
        name: "Go",
        price: 12,
        yearlyPrice: 9,
        period: "month",
        description: "For teams and creators who need more polls, better analytics, and longer retention.",
        badge: "Popular",
        cta: "Upgrade to Go",
        ctaVariant: "solid",
        limits: {
            authPolls: 40,
            anonPolls: 8,
            questionsPerPoll: 15,
            optionsPerQuestion: 8,
            analyticsRetention: "30 days",
            responseHistory: 1000,
            maxRespondentsPerPoll: 500,
            customBranding: false,
            exportResults: true,
            prioritySupport: false,
            apiAccess: false,
            webhooks: false,
        },
        features: [
            { label: "40 authenticated polls / month", included: true },
            { label: "8 anonymous polls / month", included: true },
            { label: "Up to 15 questions per poll", included: true },
            { label: "500 respondents per poll", included: true },
            { label: "Advanced analytics (30-day retention)", included: true },
            { label: "1,000 response history", included: true },
            { label: "Shareable poll links", included: true },
            { label: "Real-time response updates", included: true },
            { label: "Export results (CSV / JSON)", included: true },
            { label: "Poll scheduling", included: true },
            { label: "Custom branding", included: false },
            { label: "API access", included: false },
            { label: "Priority support", included: false },
        ],
    },
    {
        id: "pro",
        name: "Pro",
        price: 29,
        yearlyPrice: 24,
        period: "month",
        description: "Unlimited power — full analytics, long-term storage, API access, and priority everything.",
        badge: null,
        cta: "Go Pro",
        ctaVariant: "accent",
        limits: {
            authPolls: 100,
            anonPolls: 40,
            questionsPerPoll: 50,
            optionsPerQuestion: 12,
            analyticsRetention: "unlimited",
            responseHistory: -1, // unlimited
            maxRespondentsPerPoll: -1, // unlimited
            customBranding: true,
            exportResults: true,
            prioritySupport: true,
            apiAccess: true,
            webhooks: true,
        },
        features: [
            { label: "100 authenticated polls / month", included: true },
            { label: "40 anonymous polls / month", included: true },
            { label: "Up to 50 questions per poll", included: true },
            { label: "Unlimited respondents per poll", included: true },
            { label: "Full analytics history (unlimited)", included: true },
            { label: "Unlimited response history", included: true },
            { label: "Shareable poll links", included: true },
            { label: "Real-time response updates", included: true },
            { label: "Export results (CSV / JSON)", included: true },
            { label: "Poll scheduling", included: true },
            { label: "Custom branding", included: true },
            { label: "REST API access", included: true },
            { label: "Webhooks", included: true },
            { label: "Priority support", included: true },
        ],
    },
];

/** Quick helper to look up a tier by id */
export const getTier = (id) => PRICING_TIERS.find((t) => t.id === id);

/** Comparison table rows — used by the pricing page */
export const COMPARISON_ROWS = [
    { label: "Authenticated polls / mo", key: "authPolls" },
    { label: "Anonymous polls / mo", key: "anonPolls" },
    { label: "Questions per poll", key: "questionsPerPoll" },
    { label: "Options per question", key: "optionsPerQuestion" },
    { label: "Respondents per poll", key: "maxRespondentsPerPoll" },
    { label: "Analytics retention", key: "analyticsRetention" },
    { label: "Response history", key: "responseHistory" },
    { label: "Export results", key: "exportResults" },
    { label: "Custom branding", key: "customBranding" },
    { label: "API access", key: "apiAccess" },
    { label: "Webhooks", key: "webhooks" },
    { label: "Priority support", key: "prioritySupport" },
];
